[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = ""

[deploy]
startCommand = ""
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1 